import math
from dataclasses import dataclass
from typing import List

# ============================================================
# CONFIGURACIÓN: MODO "EXPLORADOR" (Permisivo)
# ============================================================
EDOS = [12, 17, 19, 22, 24, 31, 41, 43, 46, 53, 58, 72, 80, 87]

# Ahora toleramos mucha aspereza (75% de un semitono) en límites altos
# para permitir que se vean colores exóticos.
HIGH_LIMIT_ROUGHNESS_TOLERANCE = 0.75 

# Ignorar intervalos minúsculos (ruido de afinación)
MIN_INTERVAL_CENTS = 35.0 

# ============================================================
# MATH CORE
# ============================================================
def calculate_raw_roughness(ratio: float) -> float:
    freq_base = 261.63
    freq_ratio = freq_base * ratio
    N = 10
    R = 0.0
    for i in range(1, N + 1):
        for j in range(1, N + 1):
            p1 = freq_base * i; p2 = freq_ratio * j
            # Timbre musical estándar
            a1 = 1.0 / (i ** 1.5); a2 = 1.0 / (j ** 1.5)
            f_min = min(p1, p2); df = abs(p1 - p2)
            cbw = 0.24 * (f_min + 25.0); x = df / cbw
            term1 = math.exp(-3.5 * x); term2 = math.exp(-5.75 * x)
            dis = (a1 * a2) * (term1 - term2)
            R += max(dis, 0.0)
    return R

MAX_REF_ROUGHNESS = 1.0
def normalize_roughness(ratio: float) -> float:
    return calculate_raw_roughness(ratio) / MAX_REF_ROUGHNESS

def get_prime_limit(n: int) -> int:
    if n <= 1: return 1
    d = 2; temp = n; limit = 1
    while d * d <= temp:
        while temp % d == 0: limit = max(limit, d); temp //= d
        d += 1
    if temp > 1: limit = max(limit, temp)
    return limit

def gcd(a, b):
    while b: a, b = b, a % b
    return a

@dataclass
class RatioInfo:
    n: int; d: int; limit: int; cents: float; norm_roughness: float; priority: int

def calibrate_system():
    global MAX_REF_ROUGHNESS
    MAX_REF_ROUGHNESS = calculate_raw_roughness(16.0 / 15.0)
    print(f"// Calibrated Semitone Roughness: {MAX_REF_ROUGHNESS:.4f}")

# ============================================================
# GENERACIÓN DE BASE DE DATOS
# ============================================================
def generate_database() -> List[RatioInfo]:
    db = []; seen = set()
    max_denom = 60
    
    for d in range(1, max_denom + 1):
        for n in range(1, int(d * 2.1)): 
            c = gcd(n, d); nn, dd = n//c, d//c
            val = nn / dd
            if val < 1.0 or val >= 2.0: continue
            if (nn, dd) in seen: continue
            seen.add((nn, dd))
            
            lim = max(get_prime_limit(nn), get_prime_limit(dd))
            if lim > 23: continue # Subimos un poco el límite de primos aceptados

            norm_r = normalize_roughness(val)
            cents = 1200.0 * math.log2(val)
            
            # PRIORIDAD:
            # Forzamos que 3 y 5 ganen siempre la etiqueta si están disponibles.
            prio = 10
            if nn == 1 or dd == 1: prio = 0
            elif lim <= 3: prio = 1
            elif lim <= 5: prio = 2
            elif lim <= 7: prio = 3
            elif lim <= 11: prio = 4
            else: prio = 5
            
            if nn > 45 or dd > 45: prio += 1

            db.append(RatioInfo(nn, dd, lim, cents, norm_r, prio))
    
    db.append(RatioInfo(2, 1, 1, 1200.0, 0.0, 0))
    return db

def emit_cpp(edos):
    calibrate_system()
    database = generate_database()
    
    print("// AUTOGENERATED HARMONIC LUTS (Permissive High-Limits)")
    
    for edo in edos:
        step_size = 1200.0 / edo
        print(f"constexpr HarmonicStep harmonicLUT_{edo}[{edo}] = {{")
        
        for step in range(edo):
            target_cents = step * step_size
            
            # 1. Filtro vecindad
            candidates = [r for r in database if abs(r.cents - target_cents) < (step_size * 0.6) or abs((1200-r.cents) - target_cents) < (step_size * 0.6)]
            
            if not candidates:
                print(f"    {{ LIMIT_COMPLEX, 0, {step}, 1 }}, // Step {step} (Orphan)")
                continue

            # 2. Selección del Mejor
            best_metric = 99999.0
            best_cand = candidates[0]
            
            for cand in candidates:
                dist = abs(cand.cents - target_cents)
                if dist > 600: dist = 1200 - dist
                
                # Métrica: Prioridad pesa, pero dejamos margen al error
                metric = (cand.priority * 500.0) + (cand.norm_roughness * 50.0) + dist
                
                if metric < best_metric:
                    best_metric = metric
                    best_cand = cand
            
            # 3. FILTRO MUY RELAJADO
            final_limit_str = f"LIMIT_{best_cand.limit}"
            is_complex = False
            
            # Solo marcamos COMPLEX si es basura de afinación
            if best_cand.cents < MIN_INTERVAL_CENTS and best_cand.cents > 0.01:
                is_complex = True

            # O si es EXTREMADAMENTE áspero (Nivel Semitono)
            elif best_cand.norm_roughness > 0.85:
                 is_complex = True
            
            # Tambien si es mayor de 17
            if best_cand.limit > 17:
                is_complex = True

            if is_complex and best_cand.n != 1:
                final_limit_str = "LIMIT_COMPLEX"
            
            # 4. Consonancia para el Firmware
            # Mapeamos [0.0 - 0.85] -> [255 - 20]
            # Dejamos que el firmware atenúe, no matamos aquí.
            cons_score = 1.0 - best_cand.norm_roughness
            
            # Pequeño boost a límites bajos para asegurar estabilidad
            if best_cand.limit <= 5: cons_score += 0.2
            
            if cons_score > 1.0: cons_score = 1.0
            if cons_score < 0.1: cons_score = 0.1 # Suelo mínimo
            
            if final_limit_str == "LIMIT_COMPLEX":
                cons_byte = 0 # Complex sí apaga
            else:
                cons_byte = int(cons_score * 255)

            ideal = round(best_cand.cents / step_size) % edo
            max_err = max(1, int(45.0 / step_size)) # Tolerancia amplia

            debug_info = f"// {step}: {best_cand.n}/{best_cand.d} (Lim:{best_cand.limit}, R:{best_cand.norm_roughness:.2f})"
            print(f"    {{ {final_limit_str}, {cons_byte}, {ideal}, {max_err} }}, {debug_info}")

        print("};\n")

    print("constexpr HarmonicLUTDesc HARMONIC_LUTS[] = {")
    for edo in edos:
        print(f"    {{ {edo}, harmonicLUT_{edo} }},")
    print("};")

if __name__ == "__main__":
    emit_cpp(EDOS)